### PR TITLE
fix: Always Capture App Instance Id

### PR DESCRIPTION
**Pull request by BrandonStalnaker**
## Summary
 - Update the kit to always gather profile information no matter if we are forwarding server side or not

 ## Testing Plan
 - Tested end to end to confirm functionality

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-5075

### CODE REVIEW

**Review by einsteinx2 — APPROVED** [review]
LGTM, this is the same approach as the iOS SDK.

**Comment by einsteinx2** [comment]
So your change looks fine, but the tests are falling due to a bunch of missing methods somehow? 

```
com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testShippingInfoCommerceEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testEmptyEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testScreenNameSanitized FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testNameStandardization FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testPaymentInfoCommerceEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testPromotionCommerceEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testCommerceEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59

com.mparticle.kits.GoogleAnalyticsFirebaseGA4KitTest > testCheckoutOptionCommerceEvent FAILED
    java.lang.NoSuchMethodError at GoogleAnalyticsFirebaseGA4KitTest.kt:59
```

**Comment by einsteinx2** [comment]
The last commits passed, so not sure why now there is a problem...

**Comment by BrandonStalnaker** [comment]
Yeah I couldn't see a reason for the failure so I was hoping Mark could take a look for me, which he's doing now.

**Review by markvdouw — APPROVED** [review]

**Pull request merged**
